device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.F1Metric
    device: ${metrics.device}
inference: [] # metrics that are calculated during inference (eval)
