train:
  data_object:
    _target_: src.transforms.CTGANTransform
  labels:
    _target_: src.transforms.OneHot # unused
    num_classes: 2

inference:
  data_object:
    _target_: src.transforms.CTGANTransform
  labels:
    _target_: src.transforms.OneHot # unused
    num_classes: 2
