defaults:
  - model: tgan
  - metrics: gan
  - datasets: diabetes # placeholder
  - dataloader: default # placeholder
  - transforms: gan # placeholder
  - _self_
inferencer_class:
  _target_: src.trainer.GANInferencer
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "tgan" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/tgan/checkpoint-epoch700.pth" # path to the pretrained model
  number_of_samples: 768
  # type: 0
